version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: ${DATABASE_HOST}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  web:
    build: .
    container_name: messaging_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/messaging_app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
