# Generated by Django 4.2.17 on 2024-12-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants_id',
            new_name='participants',
        ),
    ]
